repository:
  # Базовые настройки
  has_wiki: false
  has_issues: true
  has_discussions: false

  # Настройки веток
  default_branch: main
  allow_rebase_merge: false
  delete_branch_on_merge: true
  allow_forking: true

  # Безопасность
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
